sudo: required
services:
    - docker

before_install:
    - docker build -t rushikeshdocker/docker-react -f Dockerfile.dev .

script:
    - docker run rushikeshdocker/docker-react npm run test -- --coverage

Deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-879010918808"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
