sudo: required
services:
    - docker

before_install:
    - docker build -t rushikeshdocker/docker-react -f Dockerfile.dev .

script:
    - docker run rushikeshdocker/docker-react npm run test -- --coverage
